apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: qu6o0w9hl8.ap-northeast-1.aws.clickhouse.cloud
      port: 8443
      protocol: https
      username: dev_ro3
      defaultDatabase: analytics
    secureJsonData:
      password: $__env{CLICKHOUSE_PASSWORD}
    editable: true
