apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: ${CLICKHOUSE_HOST}
      port: 8443
      protocol: https
      username: ${CLICKHOUSE_USER}
      defaultDatabase: analytics
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true
